### ISSUE TITLE
Wrong GridPos for nested row

### ISSUE THREAD

**Issue by tubbs** [burnbright/silverstripe-gridstructuredcontent#6]
When nested rows are used the GridPos indice is not update accordingly.

In GSCRenderer, line 29, in my opinion, you should change 
*protected function renderRows($rows, ArrayIterator $splitcontent, $pos = -1)*
by
*protected function renderRows($rows, ArrayIterator $splitcontent, &$pos = -1)*

**Comment by jedateach** [comment]
fix has been merged in #7
